name: Test

on:
  pull_request: # (1-2) Pull Requestの作成時にこのワークフローを実行
    branches: [ develop, master ]  # developとmasterブランチへのPR時に実行

jobs:
  build:

    runs-on: ubuntu-latest #(2)ubuntuを利用する

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci

    - name: Build
      env:
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        REACT_APP_X_API_KEY: ${{ secrets.REACT_APP_X_API_KEY }}
        REACT_APP_BASE_URL: Yumemi
      run: npm run build --if-present # (3)Reactアプリをビルドする
    - run: npm test # (4)テストを実行する